apiVersion: v1
kind: Service
namespace: nodeapp
metadata:
  name: nodeapp-service
spec:
  selector:
    app: nodeapp
  type: NodePort
  ports:
  - name: http
    nodePort: 31110
    port: 80
    targetPort: 3000
    protocol: TCP